### ISSUE TITLE
swiftc 2.2-dev has AnyObject problems on Linux

### ISSUE THREAD

**Issue by timburgess** [aleph7/HDF5Kit#15]
With the new build, using swiftc 2.2-dev (the snapshot release) <code>Dataset.swift</code> fails when a [Double], [Float], etc. is returned when the function return type definition is [AnyObject]. The good news is that other than that, HDF5Kit builds on Linux (Ubuntu 15.10)

**Comment by aleph7** [comment]
Fixed with https://github.com/aleph7/HDF5Kit/commit/c55628ef569050a17aa4607dfd2e6bd54f45b944
