### ISSUE TITLE
Problem reading columns within a group's dataset

### ISSUE THREAD

**Issue by dribbadev** [aleph7/HDF5Kit#17]
I'm trying to read a dataset from a group. This dataset is composed by 47033 rows x 2 columns. Using the read() functions I just get a 94066 array. How can I get the right object? Thanks.

**Comment by aleph7** [comment]
Extracting an array of arrays would be inefficient, especially for higher-dimensional data. What you need to do is `array[col + row * 2]` for accessing column `col` and row `row`. You could also use a matrix class like the one in [Upsurge](https://github.com/aleph7/Upsurge)
