### ISSUE TITLE
Port to Swift 3.0

### ISSUE THREAD

**Issue by adamjones1** [aleph7/HDF5Kit#19]

**Comment by aleph7** [comment]
Done!

**Comment by kazoo-kmt** [comment]
I installed HDF5Kit (0.2.0) via CocoaPods to work on Deep Learning on iPhone. When I opened xcworkspace file, it said "Convert to Current Swift Syntax?". After the conversion, there were a lot of errors. Are you sure this works for Swift 3.0?

**Comment by aleph7** [comment]
I just tried master with Xcode 8.1 and everything works fine. Can you post one of the errors you get? You can also try pointing the Podfile to master.

**Comment by kazoo-kmt** [comment]
Tried again with pointing the Podfile to master. Just got a typical error "Convert to Current Swift Sytax?"

> The target “HDF5Kit” contains source code developed with an earlier version of Swift.
> 
> Choose “Convert” to update the source code in this target to the latest SDKs. You will be given the choice to use Swift 2.3 syntax or update to Swift 3.
> 
> This action can be performed later using “Convert to Current Swift Syntax” in the Edit menu.

My Podfile is like this.
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'HDF5Kit-test' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HDF5Kit-test
  pod 'HDF5Kit', :git => 'https://github.com/aleph7/HDF5Kit.git'

end
```

**Comment by aleph7** [comment]
See how it's done in https://github.com/venturemedia/intune-features Swift3 branch. Works there.

**Comment by kazoo-kmt** [comment]
Sorry, but I'm still not sure. Which branch and which file are you talking about?

**Comment by kazoo-kmt** [comment]
This finally works for me.

```
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target ‘hdf5’ do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks


  # Pods for HDF5Kit
  pod ‘HDF5Kit’

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```

**Comment by aleph7** [comment]
If you update to CocoaPods 1.1.0 Swift 3 is the default. Either way I'm glad you figured it out!
