### ISSUE TITLE
StringAttribute.read() only returns 11 characters

### ISSUE THREAD

**Issue by kazoo-kmt** [aleph7/HDF5Kit#22]
It's a continued topic from #21.

The output should be variable length, but it returns fixed length string (maximum: 11 characters) when I use `read()`. Are there any ways to fix this? 

The current output `Optional(["convolution", "activation_", "convolution", "activation_", "maxpooling2", "dropout_1", "flatten_1", "dense_1", "activation_", "dropout_2", "dense_2", "activation_"])`
should be 
`Optional(["convolution2d_1", "activation_1", "convolution2d_2", "activation_2", "maxpooling2d_1", "dropout_1", "flatten_1", "dense_1", "activation_3", "dropout_2", "dense_2", "activation_4"])`

I'm not 100% sure, but in `Source/StringAttribute.swift`,  line49 somehow converts each string's data to maximum 11 characters length string. That invokes a wrong result mentioned here.
https://github.com/aleph7/HDF5Kit/commit/a6b4b864f02c063addb6f36c4a0bf9b52b84e161#commitcomment-19898264

**Comment by aleph7** [comment]
Ok, I had a mistake in my code. Try now.

**Comment by kazoo-kmt** [comment]
Thank you very much. This seems work although I had an issue when I install HDF5Kit via CocoaPods. I'll let you know if it succeeds.

Also, are there any ways to get the attribute name itself such as "layer_names" or "weight_names"?

**Comment by aleph7** [comment]
No problem. You will need to point your Podfile to master until we make a release tag.

I don't think there is a way of getting the dataset names but if you find the C API for it I can add it.

**Comment by kazoo-kmt** [comment]
Thank you. Now `pod install` works. For reading the dataset names, you may be able to use `H5Iget_name`.
http://stackoverflow.com/questions/22798731/how-can-one-get-the-name-of-an-hdf5-dataset-through-the-c-or-c-api

**Comment by aleph7** [comment]
Feel free to open another issue for that.
