### ISSUE TITLE
Add support for shape property in dataset and support for read function that returns multi-dimensional array

### ISSUE THREAD

**Issue by kazoo-kmt** [aleph7/HDF5Kit#23]
Dataset sometimes includes multi-dimensional array. For example, a weights parameter of convolution layer has 4 axes (e.g. 3, 3, 1, 32). In h5py, `group[parameter_name]` returns multi-dimensional array and `group[parameter_name].shape` returns a tuple like (3, 3, 1, 32). To handle multi-dimentional operation, I need this support. 

Regarding for read function that returns multi-dimensional array, related code in h5py might be found here: https://github.com/h5py/h5py/blob/master/h5py/h5d.pyx#L145

Regarding for shape property, it use `get_space()`that uses `SpaceID(H5Dget_space(self.id))` and `get_simple_extent_dims()`: https://github.com/h5py/h5py/blob/master/h5py/h5d.pyx#L126

I really need these API. Please let me know if you have any other ways to get them. Thank you for your support!

**Comment by kazoo-kmt** [comment]
For the second part (shape property), I now found that I can use `dataSet.space.dims` to get the information. I'm still not sure how to get the multi-dimensional array.

**Comment by aleph7** [comment]
You can use `read` it will flatten the data into a 1-dimensional array but then you can use Upsurge if you want to perform tensor/matrix operations on it.

**Comment by kazoo-kmt** [comment]
After getting multi-dimensional array, I'd like to do `swapaxes` operation. 
https://docs.scipy.org/doc/numpy/reference/generated/numpy.swapaxes.html

Does Upsurge have that method?

**Comment by kazoo-kmt** [comment]
I can do manually like this:

    var newArray = Array<T>()

    if ((axis1 == 0 && axis2 == 1) || (axis1 == 1 && axis2 == 0)) {

      for j in 0..<dimensionOfArray[1] {
        for i in 0..<dimensionOfArray[0] {
          for k in 0..<dimensionOfArray[2] {
            for l in 0..<dimensionOfArray[3] {
              newArray.append(originalArray[i*dimensionOfArray[1]*dimensionOfArray[2]*dimensionOfArray[3] + j*dimensionOfArray[2]*dimensionOfArray[3] + k*dimensionOfArray[3] + l])
            }
          }
        }
      }
